### ISSUE TITLE
Launch error (c0000005) with 1.13c

### ISSUE THREAD

**Issue by artifoxel** [xPh03n1x/eastern-sun-hd#1]
I've tried starting `Diablo II\ESHD\Game.exe` from 1.14d base install, but I get data corrupt errors for:

- d2data.mpq
- d2sfx.mpq
- d2char.mpq

<img src="https://user-images.githubusercontent.com/45717702/171950885-be2f5899-863b-4fa0-b346-8a864b07bbfa.png" width="200" />

If use a 1.13c base install (or replace the .mpq with 1.13c version), I still get an error:

<img src="https://user-images.githubusercontent.com/45717702/171934489-fa37eb2c-b5dc-4881-b8c3-423ef429844f.png" width="200" />

I've tried adjusting compatiblility, DEP, dpi settings on the exe properties, and combinations of shortcut switches `-direct -txt -w -3dfx`, but the error remains.

Any help appreciated! 🦊

**Comment by xPh03n1x** [comment]
There are errors related to your Diablo 2 instance, not to the Eastern Sun project. As such, I cannot provide you with assistance regarding them.

**Comment by artifoxel** [comment]
Hi @xPh03n1x, my Diablo II instance is a fresh installation of 1.14d (official download and patch) and the mpq errors still occur. 

Have you tested the release build recently?
